# -*- coding: UTF-8 -*-
__author__ = 'Joynice'
import pymysql

SECRET_KEY = 'Joynice'
DEBUG = True
THREADED = True

MYSQL_HOST = '10.63.2.199'
MYSQL_PORT = 3306
MYSQL_DATABASE = 'shici'
MYSQL_USERNAME = 'xxxxx'
MYSQL_PASSWORD = 'xxxxx'

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(MYSQL_USERNAME, MYSQL_PASSWORD, MYSQL_HOST, MYSQL_PORT, MYSQL_DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_COMMIT_ON_TEARDOWN = False
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_MAX_OVERFLOW = 20
SQLALCHEMY_ECHO = False